stages:
  - build
  - deploy

build:
  stage: build
  only:
    - master
  image: rust:latest
  script:
    - rustup target install wasm32-unknown-unknown
    - cargo install wasm-server-runner
    - cargo install wasm-bindgen-cli
    - cargo build --release --target wasm32-unknown-unknown
    - wasm-bindgen --out-dir ./web_build/ --no-typescript --target web ./target/wasm32-unknown-unknown/release/dice_15_puzzle.wasm
    - cp -r assets/ web_build/assets/
  cache:
    key: build_cache
    paths:
      - /usr/local/cargo
      - target
  artifacts:
    name: web_build
    paths:
      - web_build

# GitLab Pages Deploy
docker-daegunju:
  stage: deploy
  only:
    - master
  image: docker/compose:latest
  services:
    - docker:19.03.8-dind
  dependencies:
    - build
  script:
    - docker-compose down
    - docker-compose up --build -d
  artifacts:
    name: web_build
    paths:
      - web_build
  tags:
    - dind
    - daegunju-docker
