image: rust:latest

cache:
  paths:
    - .cargo

stages:
  - build
  - deploy

build:
  stage: build
  script:
    - rustup target install wasm32-unknown-unknown
    - cargo install wasm-server-runner
    - cargo install -f wasm-bindgen-cli
    - cargo build --release --target wasm32-unknown-unknown
    - wasm-bindgen --out-dir ./web_build/ --no-typescript --target web ./target/wasm32-unknown-unknown/release/dice_15_puzzle.wasm
    - cp ./index.html ./web_build/
  artifacts:
    name: web_build
    paths:
      - web_build

# GitLab Pages Deploy
docker-daegunju:
  stage: deploy
  image: docker/compose:latest
  services:
    - docker:19.03.8-dind
  dependencies:
    - build
  script:
    - docker-compose down
    - docker-compose up --build -d
  artifacts:
    name: web_build
    paths:
      - web_build
  tags:
    - dind
    - daegunju-docker
