image: rust:latest

stages:
  - build

build:
  stage: build
  script:
    - cargo build --release --target wasm32-unknown-unknown
    - wasm-bindgen --out-dir ./web_build/ --no-typescript --target web ./target/wasm32-unknown-unknown/release/dice_15_puzzle.wasm