version: '3'

services:
  dice15puzzle:
    container_name: dice15puzzle
    build: .
    restart: unless-stopped
    networks:
      - web-frontend
    labels:
      - traefik.enable=true
      - traefik.docker.network=web-frontend
      - traefik.http.services.dice15puzzle.loadbalancer.server.port=80
      - traefik.http.routers.dice15puzzle.rule=Host(`dice15puzzle.haje.org`)
      - traefik.http.routers.dice15puzzle.tls.certresolver=le
      - traefik.http.routers.dice15puzzle.entrypoints=websecure

networks:
  web-frontend:
    external: true
